#!/bin/bash
# Gemini Subagent Impersonation for Code Reviews
# Usage: ./scripts/gemini-subagent-impersonation.sh <pr-number> <subagent-name> [gemini-model]
#
# OPTIONAL: Requires Gemini CLI - Install: https://github.com/google-gemini/gemini-cli
#
# This script makes Gemini impersonate a Claude Code subagent by:
# 1. Reading the subagent's prompt from .claude/agents/<name>.md
# 2. Fetching the PR diff
# 3. Running Gemini with the subagent's identity and instructions
# 4. Posting the review as a GitHub PR comment
#
# Examples:
#   ./scripts/gemini-subagent-impersonation.sh 236 security-pentest-reviewer
#   ./scripts/gemini-subagent-impersonation.sh 236 mobile-responsive-reviewer

set -uo pipefail

PR_NUMBER="${1:-}"
SUBAGENT="${2:-}"
GEMINI_MODEL="${3:-gemini-2.5-pro}"

# Validation
if [[ -z "$PR_NUMBER" ]]; then
  echo "Usage: $0 <pr-number> <subagent-name> [gemini-model]"
  echo ""
  echo "Available models:"
  echo "  - gemini-2.5-pro (default)"
  echo "  - gemini-2.5-flash"
  exit 1
fi

if [[ -z "$SUBAGENT" ]]; then
  echo "Error: Subagent name required"
  exit 1
fi

# Check for Gemini CLI
if ! command -v gemini &> /dev/null; then
  echo "Error: Gemini CLI not found"
  echo "Install: https://github.com/google-gemini/gemini-cli"
  exit 1
fi

# Find subagent file
AGENT_FILE=".claude/agents/${SUBAGENT}.md"
if [[ ! -f "$AGENT_FILE" ]]; then
  echo "Error: Subagent not found: $AGENT_FILE"
  echo ""
  echo "Available agents:"
  find .claude/agents -name "*.md" -exec basename {} .md \; 2>/dev/null | sed 's/^/  - /' || echo "  (none found)"
  exit 1
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Gemini Subagent Impersonation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PR:       #$PR_NUMBER"
echo "Subagent: $SUBAGENT"
echo "Model:    $GEMINI_MODEL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Fetch PR data
echo "📥 Fetching PR #$PR_NUMBER data..."
DIFF=$(gh pr diff "$PR_NUMBER" 2>/dev/null)

if [[ -z "$DIFF" ]]; then
  echo "Error: Could not fetch diff for PR #$PR_NUMBER"
  exit 1
fi

PR_TITLE=$(gh pr view "$PR_NUMBER" --json title -q '.title')
PR_BODY=$(gh pr view "$PR_NUMBER" --json body -q '.body' | head -50)
CHANGED_FILES=$(gh pr diff "$PR_NUMBER" --name-only 2>/dev/null)
FILE_COUNT=$(echo "$CHANGED_FILES" | wc -l | tr -d ' ')

echo "   Title: $PR_TITLE"
echo "   Files: $FILE_COUNT changed"
echo ""

# Read subagent prompt
echo "📖 Reading subagent prompt from $AGENT_FILE..."
AGENT_PROMPT=$(cat "$AGENT_FILE")
echo "   Loaded: $(wc -l <"$AGENT_FILE") lines"
echo ""

# Build file context
FILE_CONTEXT="
**Changed Files ($FILE_COUNT files):**
\`\`\`
$CHANGED_FILES
\`\`\`
"

# Load full file contents (Gemini has 1M token window)
echo "📚 Loading full file contents..."
FULL_FILES_CONTENT=""
while IFS= read -r file; do
  [[ -z "$file" ]] && continue
  [[ ! -f "$file" ]] && continue
  [[ "$file" =~ \.(png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot|pdf)$ ]] && continue
  FILE_SIZE=$(wc -c < "$file" 2>/dev/null || echo "0")
  [[ "$FILE_SIZE" -gt 100000 ]] && continue

  FULL_FILES_CONTENT+="
━━━ FILE: $file ━━━
$(cat "$file" 2>/dev/null || echo "[Could not read file]")
"
done <<< "$CHANGED_FILES"

# Load project standards if available
PROJECT_DOCS=""
[[ -f "CLAUDE.md" ]] && PROJECT_DOCS+="
━━━ CLAUDE.md (Project Standards) ━━━
$(cat CLAUDE.md)
"

echo "🤖 Running Gemini as $SUBAGENT..."
echo ""

REVIEW=$(cat <<EOF | gemini --model "$GEMINI_MODEL"
You are impersonating a Claude Code subagent for code review.

**CRITICAL: Follow the exact identity, methodology, and output format from the agent prompt.**

━━━ YOUR IDENTITY (Subagent Prompt) ━━━

$AGENT_PROMPT

━━━ PROJECT STANDARDS ━━━

$PROJECT_DOCS

━━━ PR TO REVIEW ━━━

**PR Title:** $PR_TITLE

**PR Description:**
$PR_BODY

$FILE_CONTEXT

**Full Diff:**
\`\`\`diff
$DIFF
\`\`\`

━━━ FULL FILE CONTENTS ━━━

$FULL_FILES_CONTENT

━━━ YOUR TASK ━━━

1. Adopt the subagent identity completely
2. Study project standards (CLAUDE.md)
3. Analyze full files, not just diff hunks
4. Follow the EXACT output format from the agent prompt
5. Include verdict and file:line references

**Start your review as the subagent:**
EOF
2>&1)

if [[ $? -ne 0 ]]; then
  echo "Error: Gemini execution failed"
  echo "$REVIEW"
  exit 1
fi

echo "✅ Review generated"
echo ""

# Add metadata footer
REVIEW_WITH_META="$REVIEW

---
*🤖 Generated by Gemini ($GEMINI_MODEL) impersonating \`$SUBAGENT\`*
*📊 PR #$PR_NUMBER • $FILE_COUNT files changed*
"

# Post review
echo "📤 Posting review to PR #$PR_NUMBER..."
gh pr comment "$PR_NUMBER" --body "$REVIEW_WITH_META"

if [[ $? -eq 0 ]]; then
  echo "✅ Review posted successfully!"
else
  echo "❌ Failed to post review"
  exit 1
fi

echo ""
echo "🎉 Gemini subagent impersonation complete!"
